name: Building a CI/CD pipeline with GitHub actions

# Define when the workflow should run/ On a push to main, a PR to main or manually with workflow_dispatch 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Define some jobs that should

jobs:
  Build:
    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: echo Imagine we are compiling our code here!

DeployDev:
  name: Deploy to development
  if: gitgub.event_name == 'pull_request'
  needs: [Build]
  runs-on: ubuntu_latest
  environment:
    name: Development
    url: 'http://dev.myapp.com'
  steps:
    -name: Deploy
    runs: echo Your code is being deployed to http://dev.myapp.com!

# Our deployment to staging environment job
  DeployStaging:
    name: Deploy to staging environment
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu_latest
    environment:
      name: Staging
      url: 'http://test.myappp.com'
    steps:
      - name: Deploy
        run: echo Your code is being deployed to staging at http://test.myapp.com

# Our deployment to production job
  DeployProduction:
    name: Deploy to production
    needs: [DeployStaging]
    runs-on: ubuntu_latest
    environment:
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo The app is live at http://www.myapp.com
